version: '3.8'

services:
  rarsms:
    build: .
    container_name: rarsms-bridge
    # Configuration is loaded from config.yaml instead of environment variables
    volumes:
      - ./callsigns.txt:/app/callsigns.txt:ro
      - ./config.yaml:/app/config.yaml:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
