# RARSMS Configuration Example
# Copy this file to config.yaml and fill in your actual values

aprs:
  callsign: "RARSMS"           # Station callsign that will receive messages
  passcode: ""                 # APRS-IS passcode (calculated from callsign)
  server: "rotate.aprs2.net"   # APRS-IS server
  port: 14580                  # APRS-IS port
  filter: "t/m"               # Filter for messages only
  beacon_interval: 1800       # Beacon interval in seconds (30 minutes)

discord:
  token: ""                   # Discord bot token
  guild_id: ""               # Discord server ID
  channel_id: ""             # Channel ID for APRS messages
  use_threads: true          # Use threaded replies
  command_prefix: "!"        # Bot command prefix

database:
  url: "http://pocketbase:8090"  # PocketBase URL
  admin_email: ""                # Admin email for setup
  admin_password: ""             # Admin password for setup

logging:
  level: "info"              # debug, info, warn, error
  format: "json"             # json or text
  output: "stdout"           # stdout or file path

services:
  aprs_connector:
    enabled: true
    reconnect_delay: 30      # Seconds to wait before reconnecting
    heartbeat_interval: 300  # Heartbeat interval in seconds

  discord_bot:
    enabled: true
    reconnect_delay: 10
    message_timeout: 30      # Timeout for Discord API calls

  web_dashboard:
    enabled: true
    port: 8080

monitoring:
  health_check_port: 9090
  metrics_enabled: true
  prometheus_port: 9091