name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage pytest-cov

    - name: Create test files
      run: |
        cp config.example.yaml config.yaml
        echo -e "# Test callsigns\nTEST-1\nW4ABC\nKJ4XYZ" > callsigns.txt

    - name: Run tests with coverage
      run: |
        python -m pytest tests/ \
          --cov=protocols \
          --cov=main \
          --cov-report=xml \
          --cov-report=html \
          --cov-report=term-missing \
          --cov-fail-under=80

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      if: success()
      with:
        file: ./coverage.xml
        flags: unittests
        name: rarsms-coverage
        fail_ci_if_error: false

    - name: Upload HTML coverage report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: coverage-html-report
        path: htmlcov/
        retention-days: 30

    - name: Comment coverage on PR
      uses: py-cov-action/python-coverage-comment-action@v3
      if: github.event_name == 'pull_request'
      with:
        GITHUB_TOKEN: ${{ github.token }}
        MINIMUM_GREEN: 80
        MINIMUM_ORANGE: 70